platform :ios, '8.0'
target 'huoquan' do
    
    pod 'AFNetworking'
    pod 'IQKeyboardManager'
    pod 'JSONModel'
    pod 'SDWebImage'
    pod 'MJRefresh'
    pod 'ShareSDK3'
    pod 'ShareSDK3/ShareSDKUI'
    pod 'ShareSDK3/ShareSDKPlatforms/QQ'
    pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
    pod 'MOBFoundation'
    pod 'PureLayout'
    pod 'MagicalRecord'
    pod 'AlipaySDK-2.0'
    pod 'MBProgressHUD'
    pod 'ZBUtilities'
    pod 'BHInfiniteScrollView'
    pod 'MZTimerLabel'
    pod 'UMengAnalytics'
    pod 'SDAutoLayout'
    pod 'MLLabel'
    pod 'ZYSideSlipFilter'
    pod 'Bugly'
end
